# Generated by Django 5.0.1 on 2024-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resume2/'),
        ),
    ]
