# Generated by Django 5.0.1 on 2024-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_jobposting_hr_name_alter_company_company_hr'),
        ('jobseeker', '0007_jobseeker_email_jobseeker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='applied_jobs',
            field=models.ManyToManyField(through='jobseeker.JobApplication', to='company.jobposting'),
        ),
    ]
