# Generated by Django 5.0.1 on 2024-02-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_jobseeker_applied_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='applied_jobs',
        ),
    ]
