# Generated by Django 5.0.1 on 2024-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_jobseeker_phone_jobseeker_address_jobseeker_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
