# Generated by Django 5.0.1 on 2024-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0013_remove_jobapplication_hired_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('hired', 'Hired')], default='applied', max_length=10),
        ),
    ]
