# Generated by Django 5.0.1 on 2024-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0014_jobseeker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('hired', 'Hired')], default='applied', max_length=10),
        ),
    ]
