# Generated by Django 5.0.1 on 2024-02-03 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobposting_hr_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='hr_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_of_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
