# Generated by Django 5.0.1 on 2024-02-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_hire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hire',
        ),
    ]
